### ISSUE TITLE
.setIsAccountLinkingEnabled(true,null) with null value not linking anonymous accounts in firebase console

### ISSUE THREAD

**Issue by j2emanue** [SUPERCILEX/FirebaseUI-Android#26]
I am signing a user in anonymously and it works fine with:

`public void loadAnonymousLogin() {

        mAuth.signInAnonymously()
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            // Sign in success, update UI with the signed-in user's information
                            FirebaseUser user = mAuth.getCurrentUser();
                            Timber.d( "signInAnonymously:success:"+user.getUid());
                            proceedToActivity(MainActivity.class, null, true, false, true);                           
                        } else {
                            // If sign in fails, display a message to the user.
                            Timber.w( "signInAnonymously:failure", task.getException());
                            Toast.makeText(AuthenticationActivity.this, "Authentication failed.",
                                    Toast.LENGTH_SHORT).show();
                        }

                        // ...
                    }
                });
    }` 

now when the user doe sign in i wanted your library to actually link the accounts for me (the anonymous user and user who just signs in). so when the user is ready to sign in i call:

```
AuthUI.getInstance()
                .signOut(this)
                .addOnCompleteListener(new OnCompleteListener<Void>() {
                    public void onComplete(@NonNull Task<Void> task) {
                        // Choose authentication providers
                        List<AuthUI.IdpConfig> providers = Arrays.asList(
                                new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                                new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build(),
                                new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build()); 

startActivityForResult(
                                AuthUI.getInstance()
                                        .createSignInIntentBuilder()
                                        .setAvailableProviders(providers)
                                        .setIsSmartLockEnabled(true)
                                        .setIsAccountLinkingEnabled(true,null)
                                        .setTheme(R.style.FireBaseUIAppTheme)
                                        .setLogo(R.drawable.my_logo_white)
                                        .build(),
                                RC_SIGN_IN);
                    }
                });

```

Notice in .setIsAccountLinkingEnabled(true,null) i am passing in null for the listener. its because i do not need to update any db tables etc.  i just need to link the two accounts. we have our own DB.  but when i check firebase the account is not linked.  what am i missing ?

**Comment by SUPERCILEX** [comment]
You're signing out, don't do that. We can only know what accounts to link based on who's signed in. Hope the clarifies things!

**Comment by j2emanue** [comment]
i see what you mean. i removed the signout call if its for anonymous user.  Still having an issue let me explain my setup.  in Firebase i have single account enabled.  Anonymous user and google account is also enabled on the console.  I am expecting that when an account is linked with an anonymous account that it will show in the firebase console with the current account. so im expecting to see this in firebase when linking is complete:  
![screen shot 2561-04-01 at 12 10 57](https://user-images.githubusercontent.com/4960058/38170090-480ef804-35a6-11e8-80cf-d23f43c5e5ec.png)


but this never happens. is it because im passing null for the listener in setIsAccountLinkingEnabled ?  let me show you my new code 👍 
```

`override fun loadFireBaseUi() {

        var startFireBaseUi: () -> Unit = {
            val providers = Arrays.asList(
                    AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                    AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build(),
                    AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build())

            // Create and launch sign-in intent
            startActivityForResult(
                    AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            .setAvailableProviders(providers)
                            .setIsSmartLockEnabled(true)
                            .setIsAccountLinkingEnabled(true, null)
                            .setLocale(Locale(sharedPrefRepo!!.preferredLanguage))
                            .setTheme(R.style.FireBaseUImyappAppTheme)
                            .setLogo(R.drawable.myapp_logo_white)
                            .build(),
                    RC_SIGN_IN)
        }

        mAuth.currentUser?.let {
            if (it.isAnonymous == false)
                AuthUI.getInstance().signOut(this).addOnCompleteListener { startFireBaseUi() }
            else
                startFireBaseUi()
        } ?: run {
            startFireBaseUi() }
    }`
```


what is happening is when user is anonymous i call the above function and it opens firebaseUI and when user picks an existing acocunt to login with,  the user is able to login fine but the anonymous account is not linked when i check firebase console.  There was one other interesting thing,i notice no metaData gets sent (its null)when your linking accounts. i guess thats normal then, i dont know about that.

**Comment by SUPERCILEX** [comment]
@j2emanue You shouldn't be signing out for any of them since FirebaseUI handles all that for you, simply remove it. As for your problem, does the email account already exist? If so, there's no way to link it to the anonymous user. You'll have to delete the email account to get a successful link.

**Comment by j2emanue** [comment]
alex, thanks. its exactly as you said. i should not be signing out. and what happened in firebase console is that for a new user account that i link with anonymous user it updates the UID.  i was expecting a graphic of a anonymous user in the providers column but i did not see it.  but it does seem linked. but for existing user account no linking took place.  thanks for your help !!

**Comment by SUPERCILEX** [comment]
No problem!
