### ISSUE TITLE
Google authentication - after successfully adding google account, no callback to onActivityResult

### ISSUE THREAD

**Issue by j2emanue** [SUPERCILEX/FirebaseUI-Android#28]
here are the steps to reproduce the issue:

1. click on google signin Button.
2. choose "use another account"
3. sign in with the new account and this should bring you back to the app.
4. app only shows dark overlay and consent form or callback is not working.

then if i touch the screen the dark overlay goes away, and if i touch facebook button i get a toast saying an error has occured. at this time if i press the google button again it automatically logs me in with the account.  I tried a few apps like traveloka, stackoverflow, my own simple app with a google SOO button and glassdoor and a few others and all of them give an error after getting to option 3.  but i'd expect facebook button not to give an error at least .

**Comment by j2emanue** [comment]
I then tried it not hitting the "use another account" button but rather just clicking one of the google accounts that are offered (no smart lock , its turned off) and doing a new user signup.  held break points and saw tthatht no call back is coming to onActivityResult.  someone else tried and told me facebook is doing the same thing but i only tried google.  i do see that a IDPResponse is created for google

**Comment by SUPERCILEX** [comment]
Closing since Sam said it's a play services issue.
